name: UltraVanish
main: ga.ishadey.plugin.ultravanish.Main
version: 1.0
author: iShadey
loadbefore: [Essentials]
description: Vanish plugin!

commands:
  vanish:
    description: Hide yourself from players.
    aliases: [v, uv, ultravanish]

permissions:
  vanish.*:
    children:
      vanish.use: true
      vanish.seehidden: true
  vanish.seehidden:
    description: See people in /v!
    default: op
  vanish.use:
    description: Ability to vanish!
    default: op
  vanish.other:
    description: Ability to vanish others!
    default: op
